name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          flake8 api --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: geoguessr_analyzer/package-lock.json

      - name: Install dependencies
        working-directory: ./geoguessr_analyzer
        run: npm ci

      - name: Run linter
        working-directory: ./geoguessr_analyzer
        run: npm run lint

      - name: Build frontend
        working-directory: ./geoguessr_analyzer
        run: npm run build
